-- USER TABLE
CREATE TABLE APP_USER (
    USER_ID SERIAL PRIMARY KEY,
    FNAME VARCHAR NOT NULL,
    LNAME VARCHAR,
    EMAIL VARCHAR UNIQUE NOT NULL,
    USERNAME VARCHAR UNIQUE NOT NULL,
    PASSWORD VARCHAR NOT NULL,
    USERROLE VARCHAR(255) NOT NULL, -- ADJUST THE LENGTH AS NEEDED
    CREATED_AT TIMESTAMP DEFAULT NOW(),
    UPDATED_AT TIMESTAMP DEFAULT NOW(),
    PHONE NUMERIC UNIQUE NOT NULL -- CHANGED TO NUMERIC DATA TYPE
);

-- ADMIN TABLE (INHERITS FROM USER)
CREATE TABLE SYSTEM_ADMIN (
    ADMIN_ID INT PRIMARY KEY,
    FOREIGN KEY (ADMIN_ID) REFERENCES APP_USER(USER_ID)
);

-- RESTAURANTOWNER TABLE (INHERITS FROM USER)
CREATE TABLE RESTAURANT_OWNER (
    OWNER_ID INT PRIMARY KEY,
    FOREIGN KEY (OWNER_ID) REFERENCES APP_USER(USER_ID)
);

CREATE TABLE CUSTOMER (
    CUSTOMER_ID INT PRIMARY KEY,
    CITY VARCHAR NOT NULL,
    STREET VARCHAR NOT NULL,
    HOME_NUMBER NUMERIC NOT NULL, -- CHANGED TO NUMERIC DATA TYPE
    FOREIGN KEY (CUSTOMER_ID) REFERENCES APP_USER(USER_ID)
);

-- RESTAURANT TABLE
CREATE TABLE RESTAURANT (
    RESTAURANT_ID SERIAL PRIMARY KEY,
    OWNER_ID INT NOT NULL,
    CUISINE VARCHAR,
    CITY VARCHAR NOT NULL,
    STREET VARCHAR NOT NULL,
    BUILDING_NUMBER INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT NOW(),
    UPDATED_AT TIMESTAMP DEFAULT NOW(),
    RESTAURANT_NAME VARCHAR NOT NULL,
    FOREIGN KEY (OWNER_ID) REFERENCES RESTAURANT_OWNER(OWNER_ID)
);

-- MENU TABLE
CREATE TABLE MENU (
    MENU_ID SERIAL PRIMARY KEY,
    RESTAURANT_ID INT NOT NULL,
    MENU_NAME VARCHAR NOT NULL,
    PRICE DECIMAL(10, 2) NOT NULL,
    DESCRIPTION VARCHAR,
    CREATED_AT TIMESTAMP DEFAULT NOW(),
    UPDATED_AT TIMESTAMP DEFAULT NOW(),
    FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANT(RESTAURANT_ID)
);

-- ORDER TABLE
CREATE TABLE APP_ORDER (
    ORDER_ID SERIAL PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL,
    ORDERSTATUS VARCHAR(50) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT NOW(),
    UPDATED_AT TIMESTAMP DEFAULT NOW(),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

-- ORDER_MENU TABLE
CREATE TABLE ORDER_MENU (
    ORDER_ID INT NOT NULL,
    MENU_ID INT NOT NULL,
    QUANTITY INT NOT NULL,
    RESTAURANT_ID INT NOT NULL,
    FOREIGN KEY (ORDER_ID) REFERENCES APP_ORDER(ORDER_ID),
    FOREIGN KEY (MENU_ID) REFERENCES MENU(MENU_ID),
    FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANT(RESTAURANT_ID),
    PRIMARY KEY (ORDER_ID, MENU_ID)
);

-- CARTITEM TABLE
CREATE TABLE CART_ITEM (
    CARTITEM_ID SERIAL PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL,
    MENU_ID INT NOT NULL,
    QUANTITY INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT NOW(),
    UPDATED_AT TIMESTAMP DEFAULT NOW(),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY (MENU_ID) REFERENCES MENU(MENU_ID)
);

-- REVIEW TABLE
CREATE TABLE CUSTOMER_REVIEW (
    REVIEW_ID SERIAL PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL,
    RESTAURANT_ID INT NOT NULL,
    RATE INT NOT NULL,
    REVIEW TEXT,
    CREATED_AT TIMESTAMP DEFAULT NOW(),
    UPDATED_AT TIMESTAMP DEFAULT NOW(),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES APP_USER(USER_ID), 
    FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANT(RESTAURANT_ID) 
);
